---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myns
  labels:
    name: bggdb-deploy
  name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bgg-db
  template:
    metadata:
      name: bgg-db
      labels:
        name: bgg-db
    spec:
      volumes:
      - name: bggdb-vol
        persistentVolumeClaim:
          claimName: data-pvc
      containers:
      - name: bgg-db
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggdb-port
          containerPort: 3306
        volumeMounts:
        - name: bggdb-vol
          mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  namespace: myns
  name: bggdb-svc
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bgg-db
  ports:
  - port: 3306
    targetPort: bggdb-port
