version: '3'

volumes:
  mydb:
networks:
  mynet:

services:
  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - mydb:/var/lib/mysql
    networks:
      - mynet
  myapp:
    image: stackupiss/northwind-app:v1
    networks:
      - mynet  
    environment:
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASSWORD=changeit
    ports:
      - 3000:3000
