---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: bggns
  name: bggns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bggns
  labels:
    name: bggdb-deploy
  name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bgg-db
  template:
    metadata:
      name: bgg-db
      labels:
        name: bgg-db
    spec:
      containers:
      - name: bgg-db
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
          - name: bggdb-port
            containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  namespace: bggns
  name: bggdb-svc
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bgg-db
  ports:
  - port: 3306
    targetPort: bggdb-port

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: bggapp-secret
  namespace: bggns
  name: bggapp-secret
type: Opaque
data:
  password: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bggns
  name: bggapp-cm
data:
  db_user: "root"
  db_host: "bggdb-svc"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bggns
  labels:
    name: bggapp-deploy
  name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bgg-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: bgg-app
      labels:
        name: bgg-app
    spec:
      containers:
      - name: bgg-app
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: BGG_DB_USER
          valueFrom:
           configMapKeyRef:
            name: bggapp-cm
            key: db_user
        - name: BGG_DB_HOST
          valueFrom:
           configMapKeyRef:
            name: bggapp-cm
            key: db_host
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bggapp-secret
              key: password
        ports:
          - name: bggapp-port
            containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: bggns
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bgg-app
  ports:
  - port: 8080
    targetPort: bggapp-port
