apiVersion: v1
kind: Pod
metadata:
  name: dov-pod
  labels:
    name: dov-pod
    dept: engg
spec:
  containers:
  - name: dov-pod
    image: stackupiss/dov-bear:v2
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
