---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  labels:
    name: dov-cm
data:
  INSTANCE_NAME: dov-cm-bear

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-pod
      dept: engg
  template:
    metadata:
      name: dov-pod
      labels:
        name: dov-pod
        dept: engg
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: dov-pod
                dept: engg
            topologyKey: doks.digitalocean.com/node-id
      containers:
      - name: dov-pod
        image: stackupiss/dov-bear:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_HASH
          value: "HASH"
        envFrom:
        - configMapRef:
            name: dov-cm
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: dov-port
            containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    name: dov-pod
  ports:
  - port: 8080
    targetPort: dov-port

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dov-neptpol-deny-all
  labels:
    name: dov-neptpol-deny-all
spec:
  podSelector:
    matchLabels:
      name: dov-pod
  policyTypes:
  - Ingress
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dov-neptpol-allow-ns
  labels:
    name: dov-neptpol-allow-ns
spec:
  podSelector:
    matchLabels:
      name: dov-pod
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
         run: netshoot