apiVersion: v1
kind: Secret
metadata:
  name: mydb-secret
  labels:
    name: mydb-secret
type: Opaque
data:
  # ROOT_PASSWORD: $(echo -n "not-so-secure" | base64)
  ROOT_PASSWORD: bm90LXNvLXNlY3VyZQ==

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mydb-cluster
  labels:
    name: mydb-cluster
spec:
  replicas: 3
  secretName: mydb-secret
  mysqlVersion: "8.0"
  volumeSpec:
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      resources:
        requests: 
          storage: 1Gi
      storageClassName: do-block-storage
      
